application: ccxlv
version: 1
runtime: python
api_version: 1

handlers:

  # domain switcher
- url: /
  script: switch.py

- url: /index\.html
  script: switch.py

  # ladyOnIctProjects
- url: /loip/css/
  static_dir: ladyOnIctProjects/css/

- url: /loip/img/
  static_dir: ladyOnIctProjects/img/

  # zuidvast
- url: /zv/css/
  static_dir: zuidvast/css/

- url: /zv/img/
  static_dir: zuidvast/img/
  
- url: /zv/js/
  static_dir: zuidvast/js/  
  
- url: /index2.html
  script: zuidvast.py

  # ccxlv
- url: /ccxlv/css/
  static_dir: ccxlv/css/

- url: /ccxlv/img/
  static_dir: ccxlv/img/

  # other stuff
- url: /.*
  script: home.py
  # script: not_found.py

#- url: /(.*\.(gif|png|jpg))
#  static_files: ladyOnIctProjects/img/
#  upload: ladyOnIctProjects/img/(.*\.(gif|png|jpg))

#- url: /admin/.*
#  script: admin.py
#  login: admin

